exports = module.exports.Reset = "\x1b[0m"
exports = module.exports.Bright = "\x1b[1m"
exports = module.exports.Dim = "\x1b[2m"
exports = module.exports.Underscore = "\x1b[4m"
exports = module.exports.Blink = "\x1b[5m"
exports = module.exports.Reverse = "\x1b[7m"
exports = module.exports.Hidden = "\x1b[8m"

exports = module.exports.FgBlack = "\x1b[30m"
exports = module.exports.FgRed = "\x1b[31m"
exports = module.exports.FgGreen = "\x1b[32m"
exports = module.exports.FgYellow = "\x1b[33m"
exports = module.exports.FgBlue = "\x1b[34m"
exports = module.exports.FgMagenta = "\x1b[35m"
exports = module.exports.FgCyan = "\x1b[36m"
exports = module.exports.FgWhite = "\x1b[37m"

exports = module.exports.BgBlack = "\x1b[40m"
exports = module.exports.BgRed = "\x1b[41m"
exports = module.exports.BgGreen = "\x1b[42m"
exports = module.exports.BgYellow = "\x1b[43m"
exports = module.exports.BgBlue = "\x1b[44m"
exports = module.exports.BgMagenta = "\x1b[45m"
exports = module.exports.BgCyan = "\x1b[46m"
exports = module.exports.BgWhite = "\x1b[47m"